name: CI

on:
  # Run on all pull requests that change code.
  pull_request:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Run every time a code change is pushed.
  push:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Weekly tests
  schedule:
    # At 5:49am each Thursday
    - cron: '49 5 * * 4'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: pandoc/minimal:latest-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add luarocks5.4 make
          eval $(luarocks-5.4 path)

      - name: Install perevir
        run: luarocks-5.4 install perevir

      - name: Test
        run: make test
